---
language: node_js
node_js:
- "0.12"
install:
- git clone --depth 1 https://github.com/deconst/preparer-asset.git /tmp/preparer-asset
- sudo apt-get update && apt-get install python3.4
- sudo pip3.4 install -e git://github.com/deconst/mapping-service.git#egg=mappingservice --src /tmp/mapping-service
- sudo pip3.4 install -e git://github.com/deconst/layout-service.git#egg=layoutservice --src /tmp/layout-service
script:
- /tmp/preparer-asset/build.sh
- cd /tmp/mapping-service/ && python3.4 -m mappingservice --validate true
- cd /tmp/layout-service/ && python3.4 -m layoutservice --validate true
